name: CapeCraft
description: CapeCraft.net
author: james090500
version: 1.0.0
api-version: 1.14
main: net.capecraft.Main
commands:
  playtime:
    description: Get your playtime
  playtimetop:
    description: Get the top playtime
  afk:
    description: go afk without updating playtime
  wild:
    description: RandomTP
  rtp:
    description: RandomTP
  cape:
    description: cape command
  keepinv:
    description: Keep inv toggle
  comspy:
    description: Spy on your enemies