name: CapeCraft
description: CapeCraft.net
author: james090500
version: 1.0.0
api-version: 1.14
main: net.capecraft.Main
commands:
  playtime:
    description: Get your playtime
  playtimetop:
    description: Get the top playtime 
  wild:
    description: RandomTP
  rtp:
    description: RandomTP
  moveplayer:
    description: Moving a player